* Ruby

Ruby is an interpreted language with dynamic typing used for scripting mostly. 

#+begin_src ruby
puts "hello there"
#+end_src

is the hello world

#+begin_src ruby
puts "hello, #{1 + 1}"
# 2
#+end_src

You can put expressions inside the `#{}` and they will be evaluated. 
#+begin_src ruby
days = "Mon Tue Wed Thu Fri Sat Sun"
puts "Here are the days: #{days}"
#+end_src

Use triple quotes to write multiline strings. 

#+begin_src ruby
fat_cat = """
I'll do a list:
\t* Cat food
\t* Fishies
\t* Catnip\n\t* Grass
"""
# this will print
# I'll do a list:
#        * Cat food
#        * Fishies
#        * Catnip
#        * Grass
#+end_src

~puts~ is simply ~print~ with a newline

Get user input:

#+begin_src ruby
print "how old are you"
age = gets.chomp
puts "okay so you are #{age} years old"
#+end_src

You can convert the string to integer using 
~age = gets.chomp.to_i~, similarly, ~to_f~ makes it a float

You can accept the arguments from the user

#+begin_src ruby
first, second, third = ARGV

puts "Your first variable is: #{first}" # here, first has the 1st argument for eg
#+end_src

To accept input, one should use ~$stdin.gets.chomp~


We can read a file using:

#+begin_src ruby
filename = ARGV.first # or file_again = $stdin.gets.chomp
txt = open(filename)
puts txt.read
#+end_src


** Methods

#+begin_src ruby
def foo(x)
  x*2
end
#+end_src

The last statement is the return type.
Calling is ~foo 2~, or ~foo(2)~


Recall what blocks are, they are a block of code, that can be executed. 
All methods accept an implicit block. You can insert it whereever needed with the ~yield~ keyword

#+begin_src ruby
def surround
  puts '{'
  yield
  puts '}'
end

puts surround { puts 'hello world' }
#=> {
#=> hello world
#=> }
#+end_src

The block can also be converted to a ~proc~ object, which can be called with ~.call~ invocation.

#+begin_src ruby
def guests(&block)
  block.class #=> Proc
  block.call(4)
end
#+end_src

The arguments passed to call are given to the block

#+begin_src ruby
def guests(&block)
  block.class #=> Proc
  block.call(4)
end

guests { |n| "You have #{n} guests." }
# => "You have 4 guests."
#+end_src

By convention, all methods that return booleans end with a question mark.

By convention, if a method name ends with an exclamation mark, it does something destructive like mutate the receiver. Many methods have a ! version to make a change, and a non-! version to just return a new changed version. 
Like we saw in ~reverse!~

** Classes

Classes can be defined with a ~class~ keyword.
There are:
- class variables ~@@foo~, which are shared by all instances of this class.
- instance variables ~@foo~, which can be initialized anywhere, belong to the particular instance of the class


Basic setter:
#+begin_src ruby
def name=(name)
    @name = name
  end
#+end_src

Basic initializer:
#+begin_src ruby
 def initialize(name, age = 0)
    # Assign the argument to the 'name' instance variable for the instance.
    @name = name
    # If no age given, we will fall back to the default in the arguments list.
    @age = age
  end
#+end_src

Basic getter method
#+begin_src ruby
  def name
    @name
  end
#+end_src

Example:
#+begin_src ruby
class Foo
  def initialize(name, age=0)
    @name = name
  end

  def getName
    @name
  end
end

f = Foo.new "Foobar"
puts f.getName
# Foobar
#+end_src


The getter/setter is such a pattern that there are shortcuts to auto create them:

~attr_reader :name~

So, this works now:

#+begin_src ruby
class Foo
  attr_reader :name
  def initialize(name, age=0)
    @name = name
  end

  def getName
    @name
  end
end

f = Foo.new "Foobar"
puts f.getName
puts f.name
# Foobar
# Foobar
#+end_src

Note, when I call ~f.name = "bar"~, I am actually doing ~f.name=("bar")~ aka ~f.name= "bar"~
So I better have a method called ~name=~

Another example:
#+begin_src ruby
class Person
  attr_reader :name

  def initialize(name)
    @name = name
  end

  def name=(name)
    @name = name
  end
end

john = Person.new("John")
john.name = "Jim"
puts john.name # => Jim
#+end_src

It can also be a single line ~attr_accessor :name~

A class method uses self to distinguish from instance methods.
 It can only be called on the class, not an instance.
#+begin_src ruby
class Human
 def self.say(msg)
   puts msg
 end
end

puts Human.say "hello"
# hello
#+end_src


Variable's scopes are defined by the way we name them.
Variables that start with $ have global scope.

#+begin_src ruby
$var = "I'm a global var"
defined? $var #=> "global-variable"
#+end_src

Variables that start with @ have instance scope.

#+begin_src ruby
@var = "I'm an instance var"
defined? @var #=> "instance-variable"
#+end_src

Variables that start with @@ have class scope.
#+begin_src ruby
@@var = "I'm a class var"
defined? @@var #=> "class variable"
#+end_src

Variables that start with a capital letter are constants.
#+begin_src ruby
Var = "I'm a constant"
defined? Var #=> "constant"
#+end_src


** Modules

Including modules binds their methods to the class instances.

#+begin_src ruby
class Person
  include ModuleExample
end
#+end_src

Extending modules binds their methods to the class itself.
#+begin_src ruby
class Book
  extend ModuleExample
end
#+end_src






* Ruby misc
~2+2~
The ~+~ symbol is just syntactic sugar for the calling the ~+~ function on the number
So, these are equivalent 

#+begin_src ruby
puts 2+2
puts 2.+ 2
#+end_src

Note, in ruby, the syntax to call functions is:
~fn_name [<arg1> <arg2> ... ]~


For loop are like this elsewhere, 

#+begin_src ruby
for counter in 1..5
  puts "iteration #{counter}"
end
#+end_src

In ruby, they look like this:
#+begin_src ruby
(1..5).each do |counter|
  puts "iteration #{counter}"
end
#+end_src

This is a block. 
The 'each' method of a range runs the block once for each element of the range.
The block is passed a counter as a parameter.

The lambda nature of blocks is more easily visible by alternative equivalent form:

~(1..5).each { |counter| puts "iteration #{counter}" }~

But the general syntax to follow is:

#+begin_src ruby
array.each do |foo|
  puts foo
end
#+end_src

